# Generated by Django 3.2.4 on 2021-06-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20210618_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(blank=True, null=True, to='film.Actor'),
        ),
    ]
