# Generated by Django 3.2.4 on 2021-06-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_alter_movie_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
    ]
